### ISSUE TITLE
Should we add Courvix Network to the list of Free VPNs?

### ISSUE THREAD

**Issue by Rekulous** [nbats/FMHYedit#113]
I found this really cool service / site which provides a free VPN and OVPN config files.

It's open-source, says where they host the VPN servers, and the privacy policy for the VPN usage seems fine.

They also have a Discord server so you can ask some questions and discuss stuff there.

Links:
https://courvix.com/vpn
https://discord.gg/courvix

**Comment by nbats** [comment]
sure I'll add it to the queue
