### ISSUE TITLE
Legado, Nova Video Player, Just Player, Fermata Media Player

### ISSUE THREAD

**Issue by momobobe** [nbats/FMHYedit#141]
[Legado](https://github.com/gedoor/legado) - FOSS Android Ebook Reader `# mainly for Chinese though`

[Nova Video Player](https://github.com/nova-video-player), [Just Player](https://github.com/moneytoo/Player), [Fermata Media Player](https://github.com/AndreyPavlenko/Fermata) - FOSS Android Video Player `# all decent and powerful, recommended`

**Comment by nbats** [comment]
added all ty
