### ISSUE TITLE
"Office 365 Activators" link is broken 

### ISSUE THREAD

**Issue by Mr-Blondie** [nbats/FMHYedit#460]
In the [Office Suites](https://github.com/nbats/FMHYedit/blob/main/STORAGE.md#office-suites) section, "Office 365 Activators" link is reddit.com/r/FREEMEDIAHECKYEAH/wiki/storage#wiki_onedrive_generators but there isn't any activators.

**Comment by nbats** [comment]
Good catch I'll get it fixed
