### ISSUE TITLE
Maybe remove entries that are just search queries

### ISSUE THREAD

**Issue by lavafroth** [nbats/FMHYedit#584]
Hi. I was going through the base64 page and the entry for Burp [here](https://github.com/nbats/FMHYedit/blob/6d0f6f1afa4f3bb731e44e9959ec83b132ea25f2/base64.md?plain=1#L1370-L1372) is just a search query to a "known provider". Since this provider was already mentioned in the software list, maybe we should not keep the entry.

Same applies [here](https://github.com/nbats/FMHYedit/blob/6d0f6f1afa4f3bb731e44e9959ec83b132ea25f2/base64.md?plain=1#LL17C18-L17C20)

**Comment by nbats** [comment]
thank you, I just replaced them with new links so they shouldn't lead to the front page anymore.
